<Project Sdk="Aspire.AppHost.Sdk/13.0.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>1d197d3a-f94f-43ae-b66a-84d937b87c06</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\api\Portfolio.Api.csproj" />
  </ItemGroup>

</Project>
